const portraitImage=document.getElementById('portraitImage');
if(window.PAOPAO_PORTRAIT){portraitImage.src=window.PAOPAO_PORTRAIT;}else{portraitImage.alt='写真データを読み込めませんでした';}
document.body.classList.add('motion');
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')},{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
const progress=$('#progress');function updateProgress(){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?Math.min(1,scrollY/max)*100:0)+'%'}addEventListener('scroll',updateProgress,{passive:true});updateProgress();
const canvas=$('#ambientCanvas'),ctx=canvas.getContext('2d');let w=0,h=0,dpr=1,particles=[];
function resizeCanvas(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);particles=Array.from({length:w<700?24:50},(_,i)=>({x:Math.random()*w,y:Math.random()*h,v:.08+Math.random()*.2,a:.025+Math.random()*.08,t:i%3}))}
function drawCanvas(){ctx.clearRect(0,0,w,h);particles.forEach((p,i)=>{p.y+=p.v;if(p.y>h+20)p.y=-20;const colors=['120,247,238','255,74,112','141,120,255'];ctx.fillStyle=`rgba(${colors[p.t]},${p.a})`;const s=i%9===0?2:1;ctx.fillRect(p.x,p.y,s,s)});requestAnimationFrame(drawCanvas)}
resizeCanvas();addEventListener('resize',resizeCanvas,{passive:true});if(!matchMedia('(prefers-reduced-motion:reduce)').matches)drawCanvas();
const engine=$('#careerEngine'),portrait=$('#portraitCard');
if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches){
  engine.addEventListener('pointermove',e=>{const r=engine.getBoundingClientRect();const rx=((e.clientY-r.top)/r.height-.5)*-1.8;const ry=((e.clientX-r.left)/r.width-.5)*2.3;engine.style.transform=`perspective(1200px) rotateX(${rx}deg) rotateY(${ry}deg)`});
  engine.addEventListener('pointerleave',()=>engine.style.transform='');
  portrait.addEventListener('pointermove',e=>{const r=portrait.getBoundingClientRect();const rx=((e.clientY-r.top)/r.height-.5)*-3;const ry=((e.clientX-r.left)/r.width-.5)*3;portrait.style.transform=`perspective(900px) rotateX(${rx}deg) rotateY(${ry}deg) rotate(1.3deg)`});
  portrait.addEventListener('pointerleave',()=>portrait.style.transform='rotate(1.3deg)');
}
const STORAGE_KEY='paopao_journal_v2',BACKUP_KEY='paopao_journal_backup_v2',ARCHIVE_KEY='paopao_journal_archive_v1',list=$('#journalList'),form=$('#journalForm'),dateInput=$('#entryDate'),titleInput=$('#entryTitle'),bodyInput=$('#entryBody'),categoryInput=$('#entryCategory');
dateInput.value=new Date().toISOString().slice(0,10);
function esc(v=''){const m={'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'};return String(v).replace(/[&<>"']/g,c=>m[c])}
function loadEntries(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return []}}
function saveEntries(v){try{const previous=localStorage.getItem(STORAGE_KEY);if(previous)localStorage.setItem(BACKUP_KEY,previous);localStorage.setItem(STORAGE_KEY,JSON.stringify(v))}catch(error){alert('保存に失敗しました。JSON書き出しでバックアップしてください。')}}
function renderEntries(){const entries=loadEntries().sort((a,b)=>String(b.date).localeCompare(String(a.date))||b.created-a.created);if(!entries.length){list.innerHTML='<div class="empty-state"><div><b>まだ記録はありません。</b><span>右側の入力欄から、最初の記録を書けます。</span></div></div>';return}list.innerHTML=entries.map(e=>`<article class="entry"><div class="entry-top"><time>${esc(e.date)}</time><span class="entry-category">${esc(e.category)}</span></div><h3>${esc(e.title)}</h3><p>${esc(e.body)}</p><button data-id="${esc(e.id)}" type="button">ARCHIVE</button></article>`).join('');$$('button[data-id]',list).forEach(btn=>btn.addEventListener('click',()=>{if(!confirm('この記録をアーカイブへ移動しますか？'))return;const all=loadEntries(),target=all.find(e=>e.id===btn.dataset.id);try{const archive=JSON.parse(localStorage.getItem(ARCHIVE_KEY)||'[]');if(target){archive.push({...target,archivedAt:Date.now()});localStorage.setItem(ARCHIVE_KEY,JSON.stringify(archive))}}catch(error){}saveEntries(all.filter(e=>e.id!==btn.dataset.id));renderEntries()}))}
form.addEventListener('submit',event=>{event.preventDefault();const entry={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:dateInput.value,category:categoryInput.value,title:titleInput.value.trim(),body:bodyInput.value.trim(),created:Date.now()};if(!entry.date||!entry.title||!entry.body)return;const entries=loadEntries();entries.push(entry);saveEntries(entries);titleInput.value='';bodyInput.value='';renderEntries();list.scrollIntoView({behavior:'smooth',block:'nearest'})});
$('#exportEntries').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(loadEntries(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='paopao-journal.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$$('.journal-tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.journal-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');(tab.dataset.journalTab==='write'?$('#write'):$('#journalList')).scrollIntoView({behavior:'smooth',block:'center'})}));
renderEntries();