document.body.classList.add('motion');
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const portrait=$('#portraitImage');
if(window.PAOPAO_PORTRAIT){portrait.src=window.PAOPAO_PORTRAIT}else{portrait.alt='写真データを読み込めませんでした';}
addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')},{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
const progress=$('#progress');function updateProgress(){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?Math.min(1,scrollY/max)*100:0)+'%'}addEventListener('scroll',updateProgress,{passive:true});updateProgress();
const canvas=$('#ambientCanvas'),ctx=canvas.getContext('2d');let w=0,h=0,dpr=1,particles=[];function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);particles=Array.from({length:w<700?25:50},()=>({x:Math.random()*w,y:Math.random()*h,v:.08+Math.random()*.22,a:.03+Math.random()*.09}))}function draw(){ctx.clearRect(0,0,w,h);particles.forEach((p,i)=>{p.y+=p.v;if(p.y>h+20)p.y=-20;ctx.fillStyle=i%3===0?`rgba(120,247,238,${p.a})`:i%3===1?`rgba(255,74,112,${p.a})`:`rgba(141,120,255,${p.a})`;ctx.fillRect(p.x,p.y,i%8===0?2:1,i%8===0?2:1)});requestAnimationFrame(draw)}resize();addEventListener('resize',resize,{passive:true});if(!matchMedia('(prefers-reduced-motion:reduce)').matches)draw();
const STORAGE_KEY='paopao_journal_v2',list=$('#journalList'),form=$('#journalForm'),dateInput=$('#entryDate'),titleInput=$('#entryTitle'),bodyInput=$('#entryBody'),categoryInput=$('#entryCategory');dateInput.value=new Date().toISOString().slice(0,10);function esc(v=''){const m={'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'};return String(v).replace(/[&<>"']/g,c=>m[c])}function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return []}}function save(v){localStorage.setItem(STORAGE_KEY,JSON.stringify(v))}function render(){const entries=load().sort((a,b)=>String(b.date).localeCompare(String(a.date))||b.created-a.created);if(!entries.length){list.innerHTML='<div class="empty-state"><div><b>まだ日記はありません。</b><span>右側の入力欄から最初の記録を書けます。</span></div></div>';return}list.innerHTML=entries.map(e=>`<article class="entry"><div class="entry-top"><time>${esc(e.date)}</time><span class="entry-category">${esc(e.category)}</span></div><h3>${esc(e.title)}</h3><p>${esc(e.body)}</p><button data-id="${esc(e.id)}" type="button">DELETE</button></article>`).join('');$$('button[data-id]',list).forEach(btn=>btn.addEventListener('click',()=>{save(load().filter(e=>e.id!==btn.dataset.id));render()}))}form.addEventListener('submit',event=>{event.preventDefault();const e={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:dateInput.value,category:categoryInput.value,title:titleInput.value.trim(),body:bodyInput.value.trim(),created:Date.now()};if(!e.date||!e.title||!e.body)return;const entries=load();entries.push(e);save(entries);titleInput.value='';bodyInput.value='';render()});$('#exportEntries').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(load(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='paopao-journal.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});render();
