document.body.classList.add('motion');
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const themes={cyan:['#77f5ec','119,245,236'],violet:['#9a85ff','154,133,255'],amber:['#ffc96b','255,201,107'],green:['#67dda2','103,221,162'],coral:['#ff5d78','255,93,120']};
addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')},{passive:true});
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.11});$$('.reveal').forEach(el=>revealObserver.observe(el));
const themeObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting&&entry.intersectionRatio>.32){const [c,rgb]=themes[entry.target.dataset.theme]||themes.cyan;document.documentElement.style.setProperty('--accent',c);document.documentElement.style.setProperty('--accent-rgb',rgb)}}),{threshold:[.32,.5]});$$('.scene').forEach(el=>themeObserver.observe(el));
const progress=$('#progress');function updateProgress(){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?Math.min(1,scrollY/max)*100:0)+'%'}addEventListener('scroll',updateProgress,{passive:true});updateProgress();
const heroVisual=$('#heroVisual');if(matchMedia('(pointer:fine)').matches){heroVisual.addEventListener('pointermove',e=>{const r=heroVisual.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;heroVisual.style.setProperty('--rx',(-y*2.6)+'deg');heroVisual.style.setProperty('--ry',(x*3.3)+'deg')});heroVisual.addEventListener('pointerleave',()=>{heroVisual.style.setProperty('--rx','0deg');heroVisual.style.setProperty('--ry','0deg')})}
const dpr=Math.min(devicePixelRatio||1,2);function fit(canvas){const r=canvas.getBoundingClientRect();canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);return[c,r.width,r.height]}
const pc=$('#processCanvas');let pctx,pw,ph,t=0,particles=[];function resizeProcess(){[pctx,pw,ph]=fit(pc);particles=Array.from({length:innerWidth<700?45:85},()=>({a:Math.random()*Math.PI*2,r:60+Math.random()*220,s:.002+Math.random()*.004,z:Math.random()*100}))}function drawProcess(){t+=.012;pctx.clearRect(0,0,pw,ph);const cx=pw*.55,cy=ph*.43;pctx.save();pctx.globalCompositeOperation='lighter';for(let i=0;i<4;i++){pctx.strokeStyle=[`rgba(119,245,236,.28)`,`rgba(154,133,255,.22)`,`rgba(255,93,120,.22)`,`rgba(255,201,107,.16)`][i];pctx.lineWidth=.8;pctx.beginPath();for(let j=0;j<=140;j++){const a=j/140*Math.PI*2,x=cx+Math.cos(a+t*(.18+i*.035))*((95+i*32)),y=cy+Math.sin(a*1.24-t*(.12+i*.02))*((42+i*17));j?pctx.lineTo(x,y):pctx.moveTo(x,y)}pctx.stroke()}particles.forEach((p,i)=>{p.a+=p.s;const x=cx+Math.cos(p.a+p.z)*p.r,y=cy+Math.sin(p.a*1.13+p.z)*p.r*.42;pctx.fillStyle=i%3===0?'rgba(119,245,236,.22)':i%3===1?'rgba(255,93,120,.14)':'rgba(154,133,255,.16)';pctx.fillRect(x,y,i%7===0?2:1,i%7===0?2:1)});pctx.restore();requestAnimationFrame(drawProcess)}resizeProcess();addEventListener('resize',resizeProcess,{passive:true});drawProcess();
const ambient=$('#ambient');let actx,aw,ah,stars=[];function resizeAmbient(){[actx,aw,ah]=fit(ambient);stars=Array.from({length:innerWidth<700?40:95},()=>({x:Math.random()*aw,y:Math.random()*ah,v:.08+Math.random()*.2,s:.4+Math.random()*1.2}))}function drawAmbient(){actx.clearRect(0,0,aw,ah);stars.forEach(st=>{st.y-=st.v;if(st.y<-5){st.y=ah+5;st.x=Math.random()*aw}actx.fillStyle='rgba(255,255,255,.08)';actx.fillRect(st.x,st.y,st.s,st.s)});requestAnimationFrame(drawAmbient)}resizeAmbient();addEventListener('resize',resizeAmbient,{passive:true});drawAmbient();
const trail=$('#trail');let trctx,tw,th,trails=[];function resizeTrail(){[trctx,tw,th]=fit(trail)}resizeTrail();addEventListener('resize',resizeTrail,{passive:true});addEventListener('pointermove',e=>{trails.push({x:e.clientX,y:e.clientY,life:1});if(trails.length>45)trails.shift()},{passive:true});function drawTrail(){trctx.clearRect(0,0,tw,th);trails.forEach((p,i)=>{p.life*=.91;trctx.fillStyle=i%2?`rgba(119,245,236,${p.life*.16})`:`rgba(255,93,120,${p.life*.11})`;trctx.beginPath();trctx.arc(p.x,p.y,1+p.life*2.2,0,Math.PI*2);trctx.fill()});trails=trails.filter(p=>p.life>.03);requestAnimationFrame(drawTrail)}if(!matchMedia('(prefers-reduced-motion: reduce)').matches)drawTrail();
const REPO='SUSANO-OOO/test1',TOKEN_KEY='paopao_admin_token_v18';
function esc(v=''){const m={'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'};return String(v).replace(/[&<>"']/g,c=>m[c])}
async function loadJournal(){const target=$('#journalList');try{const res=await fetch(`https://api.github.com/repos/${REPO}/issues?state=open&labels=journal&per_page=12`,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!res.ok)throw new Error(res.status);const issues=await res.json();if(!issues.length){target.innerHTML='<div class="journal-empty"><div><b>まだ公開記録はありません。</b><span>最初のBuild Journalを準備中です。</span></div></div>';return}target.innerHTML=issues.map(issue=>{const body=String(issue.body||''),date=(body.match(/<!-- date:(.*?) -->/)||[])[1]||String(issue.created_at||'').slice(0,10),cat=(body.match(/<!-- category:(.*?) -->/)||[])[1]||'JOURNAL',clean=body.replace(/<!--.*?-->/gs,'').trim();return `<article class="entry"><div class="entry-top"><time>${esc(date)}</time><span>${esc(cat)}</span></div><h3>${esc(issue.title.replace(/^\[JOURNAL\]\s*/,''))}</h3><p>${esc(clean).replace(/\n/g,'<br>')}</p></article>`}).join('')}catch(e){target.innerHTML='<div class="journal-empty"><div><b>記録を取得できませんでした。</b><span>時間を置いて再読み込みしてください。</span></div></div>'}}
loadJournal();
const modal=$('#adminModal'),form=$('#journalForm'),connectPanel=$('#connectPanel'),connectStatus=$('#connectStatus'),saveStatus=$('#saveStatus'),tokenInput=$('#tokenInput');
function token(){return sessionStorage.getItem(TOKEN_KEY)||''}function refreshAdmin(){const connected=!!token();connectPanel.style.display=connected?'none':'block';form.classList.toggle('active',connected)}
$('#openAdmin').addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');refreshAdmin()});$('#closeAdmin').addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')});modal.addEventListener('click',e=>{if(e.target===modal)$('#closeAdmin').click()});
$('#connectButton').addEventListener('click',async()=>{const value=tokenInput.value.trim();if(!value)return;connectStatus.textContent='接続確認中...';try{const res=await fetch(`https://api.github.com/repos/${REPO}`,{headers:{Authorization:`Bearer ${value}`,Accept:'application/vnd.github+json'}});if(!res.ok)throw new Error(res.status);sessionStorage.setItem(TOKEN_KEY,value);tokenInput.value='';refreshAdmin();saveStatus.textContent='CONNECTED / このタブでは保存ボタンだけでGitHubへ直接保存できます。'}catch(e){connectStatus.textContent='接続できませんでした。対象リポジトリとIssues権限を確認してください。'}});
$('#disconnectButton').addEventListener('click',()=>{sessionStorage.removeItem(TOKEN_KEY);refreshAdmin();connectStatus.textContent='接続を解除しました。'});
$('#entryDate').value=new Date().toISOString().slice(0,10);
form.addEventListener('submit',async e=>{e.preventDefault();const tk=token();if(!tk)return refreshAdmin();const date=$('#entryDate').value,category=$('#entryCategory').value,title=$('#entryTitle').value.trim(),body=$('#entryBody').value.trim();if(!date||!title||!body)return;saveStatus.textContent='クラウドへ保存中...';try{const res=await fetch(`https://api.github.com/repos/${REPO}/issues`,{method:'POST',headers:{Authorization:`Bearer ${tk}`,Accept:'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify({title:`[JOURNAL] ${title}`,body:`<!-- date:${date} -->\n<!-- category:${category} -->\n${body}`,labels:['journal']})});if(!res.ok)throw new Error(await res.text());$('#entryTitle').value='';$('#entryBody').value='';saveStatus.textContent='保存しました。公開一覧を更新します。';await loadJournal()}catch(err){saveStatus.textContent='保存できませんでした。トークン権限またはGitHub側の設定を確認してください。'}});