import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
const baseUrl=process.env.BASE_URL||'http://127.0.0.1:4173/index.html';
const outputPrefix=process.env.OUTPUT_PREFIX||'local';
const outputDir=path.resolve('qa-artifacts');
const viewports=[{name:'desktop-1440',width:1440,height:900},{name:'tablet-1024',width:1024,height:768},{name:'mobile-390',width:390,height:844}];
await fs.mkdir(outputDir,{recursive:true});
const report={baseUrl,startedAt:new Date().toISOString(),viewports:[],failures:[]};
for(const viewport of viewports){const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:viewport.width,height:viewport.height},deviceScaleFactor:1});const page=await context.newPage();const errors=[];const failed=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(String(e)));page.on('requestfailed',r=>failed.push({url:r.url(),reason:r.failure()?.errorText||'unknown'}));const result={...viewport,errors,failed};try{await page.goto(baseUrl,{waitUntil:'networkidle',timeout:60000});await page.waitForSelector('.hero h1');await page.waitForFunction(()=>{const i=document.querySelector('.portrait-wrap img');return i?.complete&&i.naturalWidth>0&&i.naturalHeight>0},{timeout:30000});await page.waitForTimeout(1000);result.state=await page.evaluate(()=>({title:document.title,h1:document.querySelector('h1')?.innerText||'',serviceCount:document.querySelectorAll('.service').length,caseCount:document.querySelectorAll('.case').length,stepCount:document.querySelectorAll('.step').length,ctaCount:document.querySelectorAll('#contact .btn').length,portrait:{src:document.querySelector('.portrait-wrap img')?.getAttribute('src')||'',width:document.querySelector('.portrait-wrap img')?.naturalWidth||0,height:document.querySelector('.portrait-wrap img')?.naturalHeight||0},horizontalOverflow:document.documentElement.scrollWidth>innerWidth+1}));if(!result.state.h1.includes('伝わらない'))throw new Error(`${viewport.name}: hero copy missing`);if(result.state.serviceCount!==3)throw new Error(`${viewport.name}: expected 3 services`);if(result.state.caseCount!==3)throw new Error(`${viewport.name}: expected 3 experience cases`);if(result.state.stepCount!==4)throw new Error(`${viewport.name}: expected 4 process steps`);if(result.state.ctaCount<2)throw new Error(`${viewport.name}: CTA missing`);if(!/portrait\.webp/.test(result.state.portrait.src)||result.state.portrait.width<=0)throw new Error(`${viewport.name}: portrait invalid`);if(result.state.horizontalOverflow)throw new Error(`${viewport.name}: horizontal overflow`);if(errors.length)throw new Error(`${viewport.name}: console/page errors: ${errors.join(' | ')}`);if(failed.length)throw new Error(`${viewport.name}: failed requests: ${JSON.stringify(failed)}`);await page.screenshot({path:path.join(outputDir,`${outputPrefix}-${viewport.name}-home.png`),fullPage:true});}catch(error){const failure=String(error?.stack||error);result.failure=failure;report.failures.push({viewport:viewport.name,failure});try{await page.screenshot({path:path.join(outputDir,`${outputPrefix}-${viewport.name}-failure.png`),fullPage:true})}catch{}}finally{report.viewports.push(result);await browser.close()}}
report.finishedAt=new Date().toISOString();await fs.writeFile(path.join(outputDir,`${outputPrefix}-report.json`),JSON.stringify(report,null,2),'utf8');console.log(JSON.stringify(report,null,2));if(report.failures.length)process.exit(1);